### ISSUE TITLE
Measure index vs. measure number after incomplete measures

### ISSUE THREAD

**Issue by zolaemil** [umd-mith/ema#14]
How many measure do you see on the following picture?

![screenshot from 2015-12-10 10 27 26](https://cloud.githubusercontent.com/assets/4212765/11713075/f6d8a252-9f28-11e5-97be-7e9b495249ed.png)

The musical answer is 3, the technical answer _could be_ 4 (given that the technical definition of measure is tied to barlines). My understanding is that EMA measure indexes are intended to take this technical approach, but I am not sure this is the best option. 

Assume that the measure index of the first measure is N. If EMA defines four measure indexes: N, N+1, N+2, N+3, this would diverge from the generally accepted measure numbering practice, that is, assuming that the measure number of the first measure is M, people would refer to the last measure as measure M+2.

I can see the point in using measure index in some ways, on the other hand, I think it would be very useful to make the interface as intuitive as possible - perhaps the option to use either of the two would be the best.

**Comment by ahankinson** [comment]
AFAIK OMAS will simply count the number of `<measure>` elements and enumerate those. So the technical answer is simply the count of measures, not the count of barlines.

If this were encoded in MEI, you would likely need to insert a `<barLine>` object in the measure. So the encoding would reflect 3 measures.

**Comment by zolaemil** [comment]
If the API is to be independent of encoding, I think we can't rely on how it would be encoded (and note that even in MEI alone, it's possible to encode this with two different ways: with a `<barLine>` element, as you are suggesting, or with *two* incomplete `<measure metcon="false">` elemenets).

My suggestion is that relying on musical measure numbering would decouple the API from these sort of questions.

**Comment by ahankinson** [comment]
I guess what I was saying is that it wouldn't be correct to assume that the technical answer and the 'musical' answer are divergent, nor that the 'musical' answer is always intuitive. Of course we would want to err on the side of the more natural musical answer.

But I would suggest that if you're looking at two incomplete MEI `<measure>` elements, the encoder may have specified two measures for a reason. Trying to figure out where an encoder (software or person) was 'wrong' musically and automatically 'do the right thing' is an np-hard problem. ;)

**Comment by raffazizzi** [comment]
This is a great question and the API as it stands now is silent about these cases. 

I wonder why the measure is split it this way; is there an anacrusis at the beginning of the piece? I imagine there is, otherwise the first repeat would start on an off-beat (which is entirely possible, but maybe not in this repertoire?). If that is the case, then I'd be tempted to follow the technical solution (4 measures), because the "musical" answer may be that the split measure is both one measure and two halves of another two measures.

Basically, is the piece like this?
```
Y | X X X | Y Y :|: Z | X X X | Z Z :| X
```

How that example gets encoded should be irrelevant for the API: if we decide that the technical solution is better, then two measures should be counted regardless of whether they're encoded with two `<measure>` elements or with one `<measure>` and a `<barline>`. An implementation should be able to deal with both (but we all know how this can easily spiral out of control for edge cases, which is why I'd want ODD to play a role in the decisions that an MEI implementation needs to make).

In respect to usability, I think it safe to assume that EMA expressions would eventually be built from a GUI selection, or some other helpful tool, rather than being written by hand, particularly for these more complex cases.

FWIW, @ahankinson is right that Omas only counts the number of measures, and that Omas is currently the only reference implementation, but it's a simplification that should have a number of edge cases (including editorial apparatus) that are not considered yet. I think the only way to start working on the edge cases is building a decent set of tests; something I hope to kick-start soon.

**Comment by zolaemil** [comment]
> Basically, is the piece like this?
> ```
> Y | X X X | Y Y :|: Z | X X X | Z Z :| X
> ```
Yes. 

> I think it safe to assume that EMA expressions would eventually be built from a GUI selection
Just thinking about the development process, for me it would be rather useful to be able to hand-code a URI based on a simple image without having to count all the incomplete measures within the piece.

**Comment by zolaemil** [comment]
Right, I realise that `measure_labels` are already defined in the response - could they be included in the request too?

```
measureRanges ::= {measure | "M", measureLabel | startOrEnd | all / ","} | {measure | start, "-", measure | end / ","}
measureLabel ::= measure_label
```

**Comment by zolaemil** [comment]
Forget about this poor attempt to put it into BNF, but hope you get the gist of it, M12 could mean measure 12 in hte traditional sense, and 12 would be the technical measure index.

**Comment by zolaemil** [comment]
I think this can be closed now.
